// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"nonoDemo/internal/adapters/controllers"
	"nonoDemo/internal/adapters/grpcsvc"
	"nonoDemo/pkg/adapters/agin"
	"nonoDemo/pkg/adapters/grpc"
	"nonoDemo/pkg/framework"
	"nonoDemo/proto_gen/api/hello"
)

// Injectors from wire.go:

func NewGrpcServer(logger framework.Logger) *grpc.Server {
	userUsecase := grpcsvc.NewUserUsecase()
	userService := hello.NewUserService(userUsecase, logger)
	v := ProvideGrpcServices(userService)
	server := grpc.NewServer(logger, v)
	return server
}

func NewGinServer(logger framework.Logger) *agin.Server {
	helloController := controllers.NewHelloController(logger)
	v := ProvideController(helloController)
	server := agin.NewServer(v, logger)
	return server
}
