database:
  host: "localhost"
  port: "3306"
  user: "root"
  password: "123456"
  # host: "172.2.0.227"
  # port: "5432"
  # user: "postgres"
  # password: "postgres"
  name: "ads-admin"
  showsql: true

redis:
  host: 114.67.104.80
  port: 26379
  password:
  db: 1

trace:
  service_name: example
  agent_host: localhost
  agent_port: 6831
  sampling_rate: 1
log:
  writer: os.Stdout
  level: DEBUG
gin:
  listen_addr: 8080
  trace_enabled: true
  metrics_enabled: true
grpc:
  listen_addr: 9999
  trace_enabled: true
  metrics_enabled: true
